First cut at supporting argument forwarding
seattlerb/ruby_parser pull request #316
Opened 2021-02-13 01:32 UTC by presidentbeef

Adds support for argument forwarding from Ruby 2.7.

However, it needs to be a syntax error if the triple-dot argument forwarding is used anywhere but inside a method definition that sets argument forwarding (i.e., `def x(...); end`).

Looks like in MRI they set some special argument variables to do the forwarding and [check for their existence in the parser](https://github.com/ruby/ruby/blob/ruby_2_7/parse.y#L2421-L2429). (The current parser has abstracted this out into helper methods.)

Open to suggestions on how/where to track that information.

2021-02-13 22:46 UTC, zenspider commented
This looks like the right mechanism, but prolly needs to be expanded to deal with different types of locals?

```
lib/ruby_lexer.rb
331:  def is_local_id id
337:    # TODO: (dyna_in_block? && dvar_defined?(id)) || local_id?(id)
963:    tok_id = :tIDENTIFIER if tok_id == :tCONSTANT && is_local_id(token)
```

2021-02-13 23:00 UTC, zenspider requested changes

2021-02-16 18:17 UTC, presidentbeef commented on test/test_ruby_parser.rb
> +  end
Added. (Test naming and error message totally up for discussion/correction).

Should there be constants for :"*", :"**", :"&"? And where should they live? `RubyLexer`?

2021-03-19 17:53 UTC, presidentbeef commented
@zenspider Thoughts?

2021-07-14 10:50 UTC, Gbeschbacher commented
@presidentbeef @zenspider any news on that PR?

2021-08-04 03:38 UTC, zenspider commented
I overhauled this a bit... used `call_arg` and `arg` to have cleaner parser-side impl. Moved the tests into the 27 sharables (so 30 gets tested for it too). Etc. Gist is the same.

P.S. I kinda hate `s(:forward_args)`... was seriously tempted to do `s(:"...")` but I also hate quoted syms.
P.P.S. Why does that sym need quoting?

2021-08-04 09:45 UTC, closed without merging